### ISSUE TITLE
Seems to fail if web requests go through when app is first loaded

### ISSUE THREAD

**Issue by ndbroadbent** [kif-framework/AMYServer#6]
Hello,

I don't know if anyone is still maintaining this repo, but wanted to mention an issue that I'm seeing. We have an HTTP request that goes through when our app is first loaded, and only if the user is authenticated. 

This request goes through before we are able to call `server().start()` in our tests, which starts AMYServer. It seems that this initial requests breaks any future attempts to mock web requests.

I have Charles proxy open, and whenever this initial request gets fired before `server().start()`, no future requests are mocked by AmyServer (everything shows up in Charles proxy). However, if I comment out this initial request and we can call `server().start()` before any requests go through, then everything works as expected (all future HTTP requests are mocked, and nothing shows up in Charles proxy).

Can you think of anything that would cause this behaviour? If so, is there an easy fix? For now, I'm just going to add a delay before we fire off that initial request, but it's a bit of an ugly hack.

**Comment by phatmann** [comment]
@ndbroadbent Did you intend to close this issue? Are you satisfied with your hack?
